spring:
  profiles: local
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto : update
  datasource:
    url: jdbc:mysql://localhost:3306/srg
    username: root
    password: gkrduddl
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8080
