spring:
  profiles:
    active: local # 기본 환경 선택
---
server:
  port: 5080

spring:
  profiles: local
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto : update
  datasource:
    url: jdbc:mysql://localhost:3306/srg?serverTimezone=UTC
    username: srg
    password: tmfprl5$#@!
    driver-class-name: com.mysql.cj.jdbc.Driver
